### ISSUE TITLE
Is it possible to configure xmobar without command like flags or xmobarrc?

### ISSUE THREAD

**Issue by steventlamb** [jaor/xmobar#182]
This is related but not the same as https://github.com/jaor/xmobar/issues/100.

I'd like to be able to call xmobar from xmonad. I get that this is tricky due to the X loop, but I don't want to bother with the problem of serializing to the command line or writing to a file (xmobarrc).

Here's my use case:
- I use xmonad+xmobar from several computers. Each computer has a slightly different xmonad+xmobar configuration (laptops have batteries, each has different hard disks, etc.). I like to centralize these in haskell in my xmonad configuration in a repo under version control.
- My first attempt to handle this problem was to have a folder full of xmobarrc files in vc and a makefile that takes a machine name as a parameter and copies the correct xmobarrc to the location that xmonad executes from (ie. `spawnPipe "xmobar ~/.xmonad/xmobarrc`). This was tedious, led to a bunch of code duplication, and pulled my configuration out of haskell, which wasn't ideal.
- My current solution is to have a module where I create a bunch of configurations based on the machine name, serialize them to command line args, and run xmobar from xmonad with a really large string of command line arguments. You can see this here: https://github.com/steventlamb/xmonad-config/blob/master/lib/XMobarConfig.hs

I've found that as my needs grow, the types I've made in my configuration module are getting painful, and I'm recreating a lot of what's in xmobar, but crappier. This is in part because I'm new to haskell, and I could just copy and paste the types from xmobar, but I'd still have the problem of serializing to the command line or to a temporary file (xmobarrc), neither of which is ideal. I feel like there should be an easier way to do this, that I'm not seeing.

Any ideas?

**Comment by euclio** [comment]
I second this use case. I think it would be awesome if xmobar could be exposed as a library.

**Comment by prikhi** [comment]
I took a stab at this, I'm like 95% of the way there.

I started by adding xmobar as a submodule of my xmonad config & split it into a library and executable(I switched from a cabal file to a package file):
https://github.com/prikhi/xmobar/compare/master...prikhi:xmobar-library

I nested the library code under the `Xmobar` module & had to fix some compilation & flag errors along the way.

Then I could import `Xmobar.Config` into my xmonad config and build up a config:

https://github.com/prikhi/xmonad-config/blob/cc5149ace517ee9b483572704fa7cac41f71c7aa/src/StatusBar.hs#L94-L160

I then migrated xmobar's Main file over to my xmonad config, stripping out the argument & config parsing(`XmobarStub.run`). I also needed a wrapper function to create a pipe/handle for my pretty printer & to add a PipeReader command to the configs(`XmobarStub.runWithPipe`):

https://github.com/prikhi/xmonad-config/blob/master/src/XmobarStub.hs 

And since I use the `IndependentWorkspaces` & `DynamicBars` extensions, I wrote some helper functions to launch a status bar on each of my screens & to kill them on shutdown/restarts:

https://github.com/prikhi/xmonad-config/blob/cc5149ace517ee9b483572704fa7cac41f71c7aa/src/StatusBar.hs#L22-L91

Then I simply added the startup & event hooks to my main xmonad config.


The only issue I've run into is that restarting xmonad no longer works, which is a pretty big deal breaker when I'm developing the WM but not as big of a deal otherwise. When I try to run `spawn "xmonad --recompile && xmonad --restart"`, I get a `BadAccess (attempt to access private rsource denied)` error in my `.xsession-errors` file. When I comment out my xmobar forking & replace it with a simple `spawn $ "xmobar -x" ++ show screenId` call, restarts work fine again...

And now I'm kinda stuck there at the moment...

If the library/executable split is desirable, I can make a PR(although I also switched from a cabal file to a package.yaml file for stack)

**Comment by prikhi** [comment]
OK I've solved the X crashes on restarts.

I mistakenly thought the DynamicSidebar's eventHook was calling the cleanup function on shutdown, but it only happens when the screen count changes.

So I just had to make sure the recompile was successful, then kill the status bar threads & restart xmonad:

https://github.com/prikhi/xmonad-config/commit/26b8cf6184da7bb24c0ca5f09be2319ea9c75cfc

And now I can write my xmobar configs in haskell!

@jaor If you think anything from my exe/lib split branch is useful, I can send a PR:
https://github.com/jaor/xmobar/compare/master...prikhi:xmobar-library

**Comment by jaor** [comment]
> @jaor If you think anything from my exe/lib split branch is useful, I
> can send a PR: master...prikhi:xmobar-library

i haven't had time to look at it closely, but your description sounds
like something i'd like to incorporate to xmobar. it'd be nice indeed to
run xmobar as an xmonad module, and it makes used-defined plugins much
more practical.  my only worry was that we preserve the ability to
compile/run/distribute xmobar also as a self-contained executable, for
people not using it with xmonad, but from the name of your branch alone
i'm confident you were careful with that :)

so yes, feel free to open a PR for review, please.  and thanks a lot!
(but please be patient during the next 3 weeks: i'll be traveling and i
am not sure how much free time i'll have).

**Comment by prikhi** [comment]
Opened a PR but take your time :)

**Comment by jaor** [comment]
we integrated this PR, and more, a while ago. Closing!
