### ISSUE TITLE
Icons not vertically centered

### ISSUE THREAD

**Issue by menelaos** [jaor/xmobar#216]
With the upgrade to 0.23, icons are not centered correctly anymore.
Example xbm:

```c
#define sound_width 16
#define sound_height 16
static char sound_bits[] = {
   0x00, 0x00,
   0x00, 0x00,
   0x00, 0x11,
   0x80, 0x21,
   0x40, 0x49,
   0x3c, 0x51,
   0x04, 0x55,
   0x04, 0x55,
   0x04, 0x55,
   0x04, 0x55,
   0x3c, 0x51,
   0x40, 0x49,
   0x80, 0x21,
   0x00, 0x11,
   0x00, 0x00,
   0x00, 0x00};
```

**Comment by mrak** [comment]
Have you tried the new `iconOffset` option?

**Comment by menelaos** [comment]
Yes, I've used it to "fix" the problem, but it feels like an unnecessary workaround.

**Comment by mrak** [comment]
Someone else can chime in, but from what I saw with font alignment is that not all fonts render the same in respect to baseline and height. Since icons are rendering separately from the text there is bound to be some misalignment for some text/icon combinations. Thus the `textOffset` and `iconOffset` configurables :-/

**Comment by jaor** [comment]
@mrak in my tests, the icon is widely misaligned, it's not just an effect of the font chosen... i've pushed a fix to current master that should improve matters: @menelaos please let me know if that works for you.

**Comment by menelaos** [comment]
Seems to work here. Thanks for the quick response time!
