### ISSUE TITLE
Text background color

### ISSUE THREAD

**Issue by aKriJcz** [jaor/xmobar#238]
Hello,
I have problem with setting background color behind some text (with <fc> tag). It seems, that background fills area with height of text and that height is somehow wrong. I don't know whether it is issue with my font or with xmobar calculating its size. I thought that filling whole height of bar would fix it, but then I realized, that those Powerline-like arrows (which should be with maximal font height) would never connect with that filled background correctly. I have even problems with automatical vertical centering - text is shifted to the top of the bar and not centered. That should be easy to cope with with setting textOffset to some value. But that only makes background issue even worse.

Screenshot of how that looks is here:
http://imgur.com/fWYgmpx

My xmobar configuration:
http://pastebin.com/PNk0cA7m

Just ignore strange characters in configuration, I am tweaking my fonts...

**Comment by jaor** [comment]
hmmm... do you have the same kind of problems with different fonts?
alignment has been a nightmare, because XFT API seems to be less than
reliable reporting metrics (that, or i haven't understood how it
works)... perhaps this is a problem with the particular font you're
using?

**Comment by aKriJcz** [comment]
I tried few fonts with XFT and result was pretty much same. Only working solution was using XLFD definition, for example "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*". When same font is used with XFT "xft:Fixed:style=Regular:size=8", result is exactly same as in aforementioned screenshot. Most obvious difference is in filling of background area. I will try to do some more configuration changes and post screenshots, but I will be away from computer for a week, so I apologize that I won't post them soon. It sounds like XFT API has some room for improvement... Looks like old XLFD is way to go in the meantime.

**Comment by aKriJcz** [comment]
When using fixed font with XLFD (font = "-misc-fixed-*-*-*-*-10-*-*-*-*-*-*-*"), background area seems correct, but text is still shifted to the top a bit. This can be seen in image below.
![xfld](https://cloud.githubusercontent.com/assets/4060811/9057111/e243218c-3a97-11e5-9abd-0959c0f3a6ca.png)

But when same font is used with XFT (font = "xft:Fixed:style=Regular:size=8"), text is still shifted to the top and size of background area is wrong as in image below.
![xft](https://cloud.githubusercontent.com/assets/4060811/9057190/7c2f9ab4-3a98-11e5-8df6-424aa4dc05c7.png)

When using another XFT font (font = "xft:Liberation Mono for Powerline:size=8:antialias=true"), outcome is same.
![xftliber](https://cloud.githubusercontent.com/assets/4060811/9057397/156eaac0-3a9a-11e5-98b6-41e23987da5d.png)

All those fonts are changed only in top bar.

Fortunately it's only cosmetic issue, but it still saddens me that I cannot make nice Powerline-like bar (like in Vim https://github.com/powerline/powerline). Still, xmobar is by far the best status bar I have ever used ;).

**Comment by corrupt** [comment]
I just ran into the same issue. The problem is not with the fonts, rather xmobar only sets a font background as opposed to  the whole panel like dzen2 does. I'm trying to convert my working dzen2 configuration using a combination of xbm images and text to xmobar. As can be seen on these screenshots, dzen2 colors the whole panel when a background color is set, while xmobar only colors the text background. Left and right of the workspace title are small xbm images that I can manage to position somewhat accurately in xmobar. But the text background will never cover the whole bar vertically.

dzen2: 
![dzen2](https://cloud.githubusercontent.com/assets/365169/15019115/e3a0484a-121c-11e6-9720-fce1ae2ece4c.jpg)
xmobar:
![xmobar](https://cloud.githubusercontent.com/assets/365169/15019122/ec2e2874-121c-11e6-8d6c-4b84a117da38.jpg)
