### ISSUE TITLE
BatteryP not displaying the "Charging" status

### ISSUE THREAD

**Issue by alexeyzab** [jaor/xmobar#243]
Hi there,

I've been running xmobar with the following setting included:
```
                    , Run BatteryP ["BAT0"]
                        ["-t", "<acstatus>"
                        , "-L", "10", "-H", "80"
                        , "-l", "red", "-h", "green"
                        , "--", "-O", "Charging", "-o", "Battery: <left>%"
                        ] 30
```

However the -O flag doesn't seem to be working. No matter if I plug the charger in our out of my laptop, xmobar still shows the "Battery: <left>%" status.

In my ```/sys/class/power_supply/BAT0``` directory I have a ```status``` file that gets properly set to either Charging when the AC is plugged in or Discharging when it is not.

I am wondering if I am setting the options wrong somehow or if it's a bug.

I am running Arch Linux on MBA 2013, not sure if that's relevant here or not.

Thank you!

**Comment by jaor** [comment]
to check whether the battery is on AC power the monitor uses the file
`/sys/class/power_supply/AC/online` by default (we should probably use
status, but we don't): maybe that file is missing in your system? for
some system i forgot, the file was placed elsewhere in the
`/sys/class/power_supply/` directory, and we provided the monitor
configuration option `-f` (or `--online`), which is set to "AC/online"
by default.  if that happens to be the problem here, setting that
parameter could help.

**Comment by alexeyzab** [comment]
You were right, on my system it was a slightly different file. The `-f` option worked.

Thank you!
