### ISSUE TITLE
Force redraw

### ISSUE THREAD

**Issue by d125q** [jaor/xmobar#290]
Is there a way to force xmobar to redraw whenever, e.g., the volume is changed?  I am thinking of a signal or something.

**Comment by jaor** [comment]
> Is there a way to force xmobar to redraw whenever, e.g., the volume is
> changed? I am thinking of a signal or something.

xmobar reacts to SIGUSR signals:
http://projects.haskell.org/xmobar/#signal-handling

so one way woud be to have a script that changes volume and then sends
SIGUSR2 to xmobar.  that should work without modifying xmobar at all.

is that what you need?

**Comment by d125q** [comment]
Yes, that is what I want, but sending `SIGUSR2` to xmobar does not cause it to redraw.

**Comment by jaor** [comment]
then we'll have to mark this as a feature request :) although i'm not
sure if the fact that it doesn't redraw was intended or is just an
oversight.  i'll take a look as soon as i can (unless someone else beats
me, of course!)

**Comment by jaor** [comment]
another possibility: do you use dbus? if so, sending the Wakeup command
might work (using "string:Wakeup" in
http://projects.haskell.org/xmobar/#the-dbus-interface)

**Comment by skinner33** [comment]
I think the issue is not with the redraw, but with the volume plugin's inner workings:
The plugins polls regularly the current volume. Thus it does not update instantly on a volume change. Forcing a redraw will not change that.

I tried, i think about a year ago, to change that, but i did not found any callback/event-handler/... interface for pulseaudio to make the volume plugin event-based.

The workaround @d125q could use is to increase the refreshrate of the volume plugin.
Off the the top of my head one could also (ab)use stdinreader for displaying the volume, although some hacking would be required. Or try the message plugin for which a pull-request is open.

A more permanent fix within xmobar could be to change the way plugins are handled: Instead of using sleeps in each plugin thread, just use one main thread to schedule the different refresh rates and then unblock the relevant plugins (via a STM). I had this idea floating around for some time, but never came around to make a proof of concept. Initially i want to try this to reduce the number of wake ups.

**Comment by mitchellwrosen** [comment]
The `"string:Wakeup"` command does not cause a re-draw. Is it supposed to?
