### ISSUE TITLE
Xmobar does not render but seems to exist.

### ISSUE THREAD

**Issue by Fuco1** [jaor/xmobar#293]
This is quite a weird issue and I have no idea how it started, as far as I can tell it just happened randomly after a restart (so probably some package got updated).

I run xmobar from xmonad and when I look into running processes I can see it is running.  There is also "struts" allocated by xmonad, so there is an empty bar on top of the screen, but I can see the background image and xmobar does not appear.  When I toggle struts it properly expands and collapses, and when I kill xmobar from the CLI the struts "panel" collapses and no longer expands.  So I think xmobar creates a window (or preallocates? I'm not sure how X works).

Does anyone have some idea on what could cause this?  I use ubuntu 16.04, xmonad 0.12 (compiled from source) and xmobar master (compiled from source) with all extensions.

**Comment by lucianposton** [comment]
xmobar was rendering behind my background too.

The workaround that worked for me was setting lowerOnStart = False in my xmobar config.

**Comment by jaor** [comment]
yes, that should be the solution... i wouldn't call it a workaround :)
maybe we changed the default, im not sure...

On 19 Mar 2017 12:00 a.m., "lucianposton" <notifications@github.com> wrote:

xmobar was rendering behind my background too.

The workaround that worked for me was setting lowerOnStart = False in my
xmobar config.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jaor/xmobar/issues/293#issuecomment-287581206>, or mute
the thread

**Comment by Fuco1** [comment]
@lucianposton @jaor thanks both, this setting seems to work, however now my fonts are all messed up :D  But I guess that's a separate issue (something must have changed on master, before I run some quite old version).

I'm closing this as the problem is solved.
