### ISSUE TITLE
Extract out IWlib.hsc as a library?

### ISSUE THREAD

**Issue by LeifW** [jaor/xmobar#330]
I think this binding would be useful, for wanting to know about the current WiFi connection in other code (personally, I want to display this info in taffybar).
And then turning on the with_iwlib would add a dependency to this lib?
Would that make sense? Would you want maintain it, or should someone else?
e.g. https://github.com/LeifW/iwlib

**Comment by jaor** [comment]
Hi Leif,

Sounds good, and i am happy to maintain it, specially seeing that you
already did the heavy lifting :) But of course if you prefer to be the
maintainer for some reason, that's fine by me too.  Otherwise perhaps
you can just transfer ownership of that repo to my user (jaor) and i'll
publish to hackage?

**Comment by LeifW** [comment]
Done!
I didn't even know you could transfer repos on GitHub.
Thanks so much!
You'd probably want to replace me as maintainer in the .cabal file in there.
I just did "cabal init" to generate that.

**Comment by jaor** [comment]
The new lib is up and running, and already being used by xmobar.  Thanks!
