### ISSUE TITLE
kworkers filling up TopProc

### ISSUE THREAD

**Issue by alex404** [jaor/xmobar#369]
Hello,

I'm running Arch and on newer kernel versions (currently running 4.19.2) the 'TopProc' monitor spends a lot of its time reporting kworkers at 100% cpu usage. Multicpu does not report 100% usage, and when I run 'top' from the command line, the kworkers are sitting well below most of my processes. Also, this issue goes away when I run the LTS kernel (4.14.81).

I've noticed this issue for a few months (can't remember if it came with kernel 4.19 or 4.18) but I've avoided it by running the lts kernel. At this point though it doesn't seem like a problem with the kernel so it would be nice if there were a better way around this.

Thanks!

**Comment by jaor** [comment]
Hi,

Yes, I've been also suffering from this since kernel 4.19 came to my
debian sid.  I haven't looked close, but i am guessing something has
changed in how these kworker threads are reported in the /proc
filesystem (TopProc gets its info from there). I wouldn't rule out a
problem with that reporting, because i haven't changed TopProc's code
in, literally, years, so it cannot be a bug recently introduced.

A quick and dirty solution could be to introduce some regexp or list of
names to be skipped by TopProc (i remember back in the day wmtop or a
similar one did that), but i would really like to understand what's
going on.

**Comment by jaor** [comment]
i've pushed a patch that simply filters out kernel threads (identified by having ppid 0 and consuming no memory).  if someone feels strongly about displaying them, we could add a configurable boolean flag to the monitor, but i'll wait until someone feels strongly :)

**Comment by alex404** [comment]
Cheers, thanks! That's awesome!

**Comment by xoi** [comment]
It seems the cause is:

  - The name of kworker changes, as in this example:
    `kworker/0:0-events` &rarr; `kworker/0:0-mm_percpu_wq`
  - Xmobar identifies process by PID and name.

The result of the avobe is:

  1. Xmobar identifies kworker as new process when the name changed.
  1. Xmobar calculates the cpu percentage with the total amount of cpu time as amount in the moment.
  1. The calculated cpu percentage is high.

I think it is better to identify by one of the following without name.

  - only PID
  - PID and `starttime` (22nd field of `/proc/[pid]/stat`)

**Comment by jaor** [comment]
that might be a better strategy, yes, but we implemented a shorter
workaround by simply ignoring kworkers: are you still seeing them (or
want to)?

**Comment by xoi** [comment]
No, I am not seeing in the latest version; I am using an old version.
I wrote it for reference.
