### ISSUE TITLE
"Invalid configuration file" error after 0.29.5-7 upgrade

### ISSUE THREAD

**Issue by franalbani** [jaor/xmobar#392]
I did `pacman -Syu` and upgrade to **0.29.5-7**.

Now this happens:
```
$ xmobar -x 0 botbar
Invalid configuration file: "Config" (line 61, column 10):
unexpected "s"
expecting space or "Run"

(No compilation attempted: only .hs, .hsc or .lhs files are compiled)
```

Relevant config line:

`       , sepChar = "&"`

I did not modify this config and it was working for years.

**Comment by jaor** [comment]
this error typically happens when you try to use a monitor in you config
that is not supported by the compiled version of xmobar (we have lots of
extensions and most of them are optional).  i'm afraid i don't know
anything about pacman's packages, but i guess somewhere there must be a
description of what it supports...

**Comment by abhixec** [comment]
I ran into the same issue seems like weather plugin is the issue I removed the weather from command list and was able to get the xmobar back up. Still trying to figure out what in the weather command it doesn't like.

**Comment by Maeda1** [comment]
Hello,
Same issue, same line, same error as @franalbani.

**Comment by abhixec** [comment]
@Maeda1 I think the problem is that the weather plugin isn't packaged with xmobar. 
I will file a bug for it in Archlinux repository hopefully today so that the maintainer for that package is aware that he forgot to package the weather plugin.

**Comment by Maeda1** [comment]
I installed last one, still the issue. I may have something wrong on the weather command line. It was working before.
I will check this.

**Comment by abhixec** [comment]
Can you check to make sure you are on xmobar 0.29.5.10 version?
my weather command for your reference
`Run Weather "KSJC" ["-t","<station>: <tempC>C","-L","37","-H","131","--normal","green","--high","red","--low","lightblue"] 36000`

**Comment by Maeda1** [comment]
I just checked :
`, commands = [ Run Weather "LFLB" ["-t"," <tempC>°C","-L","0","-H","30","--normal","green","--high","red","--low","lightblue"] 18000`
At first sight, no mistake.

**Comment by abhixec** [comment]
Can you post link is gist to your full xmobarrc?

**Comment by Maeda1** [comment]
[file](https://framabin.org/p/?f9a23df7455a4a09#6JYpMsrPFSzSRvndFQ14DGdV2E+B6Cu7FjYH0n4mGuM=)

**Comment by jaor** [comment]
Since a couple months ago, the weather server has to be accessed via HTTPS, so the latest versions of xmobar always use the haskell conduit libraries to implement the plugin (in previous versions, conduit was only used on demand, for users that had to access weather behind a proxy).  That means that to compile xmobar with the weather plugin one needs a number of new haskell dependencies (actually, quite a lot, unfortunately).  My suspicion is that the Arch maintainer dropped support for the weather plugin in the latest version (here's nothing wrong with your configuration, and the error you get means almost for sure that xmobar is not compiled with that plugin).

**Comment by Maeda1** [comment]
OK @jaor, thanks for the explanation. I will remove this Weather command line from my secondary bar to be able to use it again.
Strange it works for @abhixec.
I will look for an external script to do that (this is not critical information for sure :) )

**Comment by franalbani** [comment]
Commenting out Weather plugin solved this issue for me.
