### ISSUE TITLE
Tighten bounds on base on latest release

### ISSUE THREAD

**Issue by vmchale** [jaor/xmobar#461]
See Hackage CI: https://matrix.hackage.haskell.org/#/package/xmobar

Thanks :)

**Comment by jaor** [comment]
Thanks Vanessa.  @psibi, looking at those, seems that in the newest
StdinReader we're using `<>`, which is not directly available in 8.2 and
8.0.  I am not sure how important is to keep compatibility with those
versions for our users, or if the fix is not too much hassle to be worth
it...

**Comment by psibi** [comment]
I think keeping support for last 3 GHC versions should be good enough. The Hackage CI shows me that it's works for the last 4 GHC versions. What do you think ?

**Comment by slotThe** [comment]
I too think that dropping 8.0 and 8.2 is probably not a big deal.

In general I believe it's a good idea to at least support the version of GHC that debian-stable uses (otherwise it might be too abrupt of a change).  According to [here](https://packages.debian.org/stable/haskell/ghc), they use GHC 8.4.4 so it should be all good!

**Comment by jaor** [comment]
i am good with that, provided no distribution out there really, really
needs us to support something older.  but even in those cases, if any, i
guess they could use a previous version of xmobar.

**Comment by jaor** [comment]
the new 0.35.1 release tightens the bounds to 8.4 or better.  thanks!
