### ISSUE TITLE
Autodetect stdin/property logging

### ISSUE THREAD

**Issue by liskin** [jaor/xmobar#517]
In https://github.com/xmonad/xmonad-contrib/pull/408 we started guiding users towards using property-based logging, but the default setup is unfortunately no longer just adding `xmobarProp` to xmonad config as xmobar uses StdinReader by default and it needs to be told to use XMonadLog explicitly. It'd be nice if we could make this easier for users again:

* when xmobar is started with stdin from /dev/stdin (this might be difficult to detect), use different defaults
* or add an option like --xmonad that would change the defaults (we can't pass `--template`, we don't want to override config, if there is one)
* something else entirely, I haven't thought this through, really

What do you think? @slotThe

**Comment by slotThe** [comment]
On Sat, Dec 19 2020 10:24, Tomáš Janoušek wrote:
> In https://github.com/xmonad/xmonad-contrib/pull/408 we started
> guiding users towards using property-based logging, but the default
> setup is unfortunately no longer just adding `xmobarProp` to xmonad
> config as xmobar uses StdinReader by default and it needs to be told
> to use XMonadLog explicitly. It'd be nice if we could make this easier
> for users again:

This definitely sounds like a good suggestion (and the README update
that I'm currently working on also presents property-based logging as a
first choice now), though right now I'm also not quite sure how to go
about it.

> * when xmobar is started with stdin from /dev/stdin (this might be
> difficult to detect), use different defaults

That does indeed sounds kind of difficult to detect; to the point where
I'm not sure it's even reasonably possible, though you know much more
about that than I do.

> * or add an option like --xmonad that would change the defaults (we
> can't pass `--template`, we don't want to override config, if there is
> one)

This sounds doable, and would certainly still be less friction rewriting
ones config file; perhaps that's already enough.  Currently the config
is parsed first and then the command line options are put on top of it;
the Runnable existential type implements Show and so we could slurp out
whether [Unsafe]StdinReader was used and replace that if necessary.  The
template string is not well typed because it's, well, a string, so there
will have to be some replace magic there.

I'll try to think about this a bit over the holidays, maybe I'll have an
epiphany.

**Comment by liskin** [comment]
It seems detecting /dev/null isn't that difficult, just fstat fd 0, stat /dev/null, compare the results.

That being said, I'm not entirely sure that defaulting to using specifically XMonadLog in that case is the best, as I can imagine other scenarios when one runs xmobar accidentally without an input but perhaps outside of xmonad. On the other hand, the window appears and says "Updating...", so as long as we print a warning to stderr or something, it shouldn't be too confusing.

**Comment by liskin** [comment]
Oh and all these variants will break horribly unless the user runs a recent xmobar. :-)

**Comment by jaor** [comment]
@slotThe @liskin any new thoughts/developments on this area? is there anything we can do in xmobar to help?

**Comment by liskin** [comment]
@jaor No new developments really. Just a matter of deciding whether to do it and the interface.

There's also an option we haven't mentioned yet: xmonad could set an environment variable like `XMONADLOG_PROP=XMonadLog` and xmobar would then default to `XPropertyLog` if the env var is set. The advantage over a command-line option is that this won't break for users who already have `XMonadLog`/`XPropertyLog` in their .xmobarrc but who don't upgrade xmobar soon enough. The disadvantage is that using envvars makes stuff less transparent and more difficult to debug.

Another thought: xmonad can ensure that the property is set before launching xmobar, so then when xmobar checks whether stdin is /dev/null (which it can also do by just checking for EOF, btw, although not sure if that can be done in Haskell without blocking) it can also check if the property's already set, and default to XMonadLog only if it is. So the logic could be something like:

```
if stdin is eof:
    if _XMONAD_LOG property is set on root window:
        default is XMonadLog
    else:
        show error that there's no valid input (StdinReader already does it, but maybe something more informative?)
else:
    default is StdinReader
```

This way we avoid defaulting to `XMonadLog` accidentally when someone launches xmobar without pipe to stdin. Except in cases where people experiment with all sorts of set up and there's a leftover _XMONAD_LOG property still set on the root window. :-)

So I guess if we care about backward compat we pick one of these variants, and if we don't then the command-line option is straightforward.

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/517
