### ISSUE TITLE
The website is not really the website

### ISSUE THREAD

**Issue by TheMC47** [jaor/xmobar#599]
https://xmobar.org/ Isn't  pointing to the xmobar website
![image](https://user-images.githubusercontent.com/23745185/149656220-a2b9571d-6898-4786-89ac-bb5c30ebe8bf.png)

**Comment by jaor** [comment]
On Sun, Jan 16 2022, Yecine Megdiche wrote:

> https://xmobar.org/ Isn't  pointing to the xmobar website
> ![image](https://user-images.githubusercontent.com/23745185/149656220-a2b9571d-6898-4786-89ac-bb5c30ebe8bf.png)

yes. that domain is due to expire in a week or so, and won't be pointing
anywhere i control anymore.  this repo will be the official homepage
from now on.

i've removed relevant references to xmobar.org in master (just left one
in the web makefile, unused).  thanks!

**Comment by liskin** [comment]
Is that a deliberate choice or was the domain out of your control already? (Just thinking if there's any point offering help or anything.)

**Comment by jaor** [comment]
On Mon, Jan 17 2022, Tomáš Janoušek wrote:

> Is that a deliberate choice or was the domain out of your control
> already? (Just thinking if there's any point offering help or
> anything.)

deliberate.  i don't want to pay for it anymore since i don't think it
serves any useful purpose, and actually the generation of the site from
the current docs would need fixing, so it'd also need maintenance
time... but i'm happy to hear opinions, of course.

**Comment by jaor** [comment]
just for the record, i've renewed the domain for one more year.  i'll
make it forward to github for now, and make a new decision next year
depending on whether it gets any use.
