### ISSUE TITLE
Advanced color name parsing

### ISSUE THREAD

**Issue by pavel-the-best** [jaor/xmobar#606]
Currently, parsing config colors is a mess: sometimes it's done this way, sometimes it's done that way, sometimes it's not done.
For example, "lightgreen" color will work in default output (X11) and with `-TPango`, but won't work with `-TAnsi` and `-TSwaybar`.
Perhaps, xmobar could use some already existing color parsing/transforming logic (I'm thinking about `colour` and `ansi-terminal` from hackage).

**Comment by jaor** [comment]
i forgot about the "bright" variant for ANSI, just pushed a patch.
with that, i think the situation is less messy, in a way, than it
seems, or at least, that there is some method in the madness: for each
format, we support the specifications valid for that format; i.e., the
16 ansi colour names, all names for terminals together with their rgb
specs, and rgba for pango/sway.  i would of course merge code somehow
unifying all naming across output formats, but i don't really see an
urgent need for it, because my impression is that it'd be rare to have
a single conf and wanting to reuse in more than one format.  but maybe
i'm just biased because i do have a separate conf for each possible
format!

**Comment by jaor** [comment]
moved to https://codeberg.org/jao/xmobar/issues/606
